apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
  labels:
    app: simple-server
spec:
  selector:
    matchLabels:
      app: simple-server
  template:
    metadata:
      labels:
        app: simple-server
    spec:
      containers:
      - name: simple-server
        # this is pointing to the local container registry
        # that kind can pull images from
        image: localhost:5000/api:latest
        ports:
        - containerPort: 8080
